### ISSUE TITLE
Feedback and questions

### ISSUE THREAD

**Issue by racer1988** [martinbanas/coordinator#1]
Thank you for your feedback.

I had a look at your framework, which is a great idea to help development and architecture sharing 😄 

I know it is not connected to any particular framework, but it shares a lot of common things with some of them.

For example, if we take VIPER, it looks to me that the `Coordinator` is reflecting the `Interactor` job.

One thing (following Viper idea) that I do not fully share is about the ViewModel.
Why the ViewModel should contain logic such as:

    func presentForgotPassword() {
        coordinator?.presentForgotPassword()
    }

I feel like these are entry point of business logic, and I would rather see them isolated (with the login service) in a `UseCase`, or whatever we want to call the business layer abstraction.

I believe that ViewModel should be defined like: A dumb model, that is immutable and knows nothing else than the data inside.

I know this adds additional layers with model and `UseCase` in order to fully split the responsability,
but it would make possible to reuse the entire model (like a `UserViewModel`) in multiple apps with different business logic (like one that has `ForgotPassword` and one that has not)

What do you think

**Comment by martinbanas** [comment]
Thanks for taking look :)

Yes, the idea behind the Coordinator overlaps with some other patterns and you can definitely find some similarities. My intention was not to tide the implementation with MVVM and I'm using it just like an example.

There is a lot of discussion about immutable / mutable ViewModels. I've been using both in my projects and I think it's better to have immutable / stateless ViewModel. I don't see too much potential in reusing ViewModels across different apps but it's definitely easer to debug and write unit tests. But it depends and sometimes it's better to not overcomplicate the solution with following strict rules.
